import "../../../styles/globals.css";
import { EditorNavbar } from "@/components/EditorNavbar";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<EditorNavbar />
				{children}
			</body>
		</html>
	);
}
