import Header from "@/components/Common/Header";
import "@/styles/globals.css";
import AuthProvider from "@/providers/AuthProvider";

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

export const revalidate = 0;

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const supabase = createServerComponentClient({ cookies });

	const {
		data: { session },
	} = await supabase.auth.getSession();

	const { data, error } = await supabase
		.from("users")
		.select("*")
		.match({ user_id: session?.user.id });

	return (
		<html lang="en">
			<body>
				<AuthProvider accessToken={session?.access_token}>{children}</AuthProvider>
			</body>
		</html>
	);
}
