import { Hero } from "@/components";
import Header from "@/components/Common/Header";
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const supabase = createServerComponentClient({ cookies });

	const {
		data: { user },
	} = await supabase.auth.getUser();

	const { data, error } = await supabase.from("users").select("*").match({ user_id: user?.id });

	return (
		<>
			<Header user={data ? data[0] : undefined} />
			{children}
		</>
	);
}
