import { Hero } from "@/components";
import "../../styles/globals.css";
import Header from "@/components/Common/Header";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Header />
				<Hero />
				{children}
			</body>
		</html>
	);
}
